// Mocks generated by Mockito 5.x from @GenerateMocks([LocalCacheService])
// in test/widget/sparkline_card_test.dart.
// Do not edit by hand.
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:equinox_flood/models/flood_data.dart' as _i2;
import 'package:equinox_flood/services/local_cache_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

/// A class which mocks [LocalCacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalCacheService extends _i1.Mock implements _i3.LocalCacheService {
  MockLocalCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Future<void> init() => (super.noSuchMethod(
        Invocation.method(#init, []),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<void> saveGaugeList(List<_i2.FloodData> gauges) =>
      (super.noSuchMethod(
        Invocation.method(#saveGaugeList, [gauges]),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<({List<_i2.FloodData> data, bool isStale})> loadGaugeList() =>
      (super.noSuchMethod(
        Invocation.method(#loadGaugeList, []),
        returnValue: Future<({List<_i2.FloodData> data, bool isStale})>.value(
            (data: <_i2.FloodData>[], isStale: true)),
      ) as Future<({List<_i2.FloodData> data, bool isStale})>);

  @override
  Future<void> appendGaugeHistory(String stationId, double currentLevel) =>
      (super.noSuchMethod(
        Invocation.method(#appendGaugeHistory, [stationId, currentLevel]),
        returnValue: Future<void>.value(),
        returnValueForMissingStub: Future<void>.value(),
      ) as Future<void>);

  @override
  Future<List<(DateTime, double)>> loadGaugeHistory(String stationId) =>
      (super.noSuchMethod(
        Invocation.method(#loadGaugeHistory, [stationId]),
        returnValue:
            Future<List<(DateTime, double)>>.value(<(DateTime, double)>[]),
      ) as Future<List<(DateTime, double)>>);
}
